### ISSUE TITLE
Does not handle modern passwords with special characters well...

### ISSUE THREAD

**Issue by gutow** [jcu-eresearch/static-plone-wget#3]
Because wget runs on the command line passwords that contain characters like $ and some other punctuation do not work. Is there a way we can quote this stuff so that wget will pass it properly.
Temporary workaround is to use simple passwords for the static_backup user. I think this is only safe on a copy running locally.

**Comment by davidjb** [comment]
Thanks for the report, great catch.  I've URL-encoded these parameters now via a shell function so the script will work with any characters in the username and password.

**Comment by gutow** [comment]
You are welcome. Thanks for maintaining this. I use it periodically to produce static backups of sites that need archiving.
